# Generated by Django 4.2.6 on 2023-10-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
