# Generated by Django 4.2.6 on 2023-10-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='details',
            field=models.CharField(max_length=82),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=255, verbose_name='service name'),
        ),
    ]
