# Generated by Django 4.2.6 on 2023-10-16 06:13

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_details_alter_service_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='service/service.jpg', storage=service.models.OverwriteStorage(), upload_to=service.models.image_upload, validators=[service.models.validate_dimension]),
        ),
    ]
