# Generated by Django 4.2.6 on 2023-10-17 10:11

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='service/service.jpg', storage=service.models.OverwriteStorage(), upload_to=service.models.image_upload, validators=[service.models.validate_dimension])),
                ('details', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='segments',
            field=models.ManyToManyField(blank=True, to='service.servicesegment'),
        ),
    ]
