# Generated by Django 4.2.6 on 2023-10-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_servicesegment_service_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesegment',
            name='title',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
