# Generated by Django 4.2.6 on 2023-10-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_servicesegment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesegment',
            name='figcaption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
