# Generated by Django 4.2.6 on 2023-10-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_alter_contactus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_us', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('offices', models.CharField(blank=True, max_length=50, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='twitter url')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='facebook url')),
                ('whatsapp_url', models.URLField(blank=True, null=True, verbose_name='linkedin url')),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
    ]
