# Generated by Django 4.2.6 on 2023-10-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='linkedin url'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='facebook url'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='twitter url'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='whatsapp_url',
            field=models.URLField(blank=True, null=True, verbose_name='whatsapp url'),
        ),
    ]
