# Generated by Django 4.2.6 on 2023-10-12 13:57

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='portfolio/project.jpg', storage=portfolio.models.OverwriteStorage(), upload_to=portfolio.models.image_upload),
        ),
    ]
