# Generated by Django 4.2.6 on 2023-10-16 06:13

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='portfolio/project.jpg', storage=portfolio.models.OverwriteStorage(), upload_to=portfolio.models.image_upload, validators=[portfolio.models.validate_dimension]),
        ),
    ]
