# Generated by Django 4.2.6 on 2023-10-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_myservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myservice',
            options={'verbose_name': 'My cart', 'verbose_name_plural': 'My cart'},
        ),
    ]
