# Generated by Django 4.2.6 on 2023-10-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='suitable_time',
            field=models.DateTimeField(verbose_name='suitable time for contact'),
        ),
    ]
